name: 'Dockerize a Quarkus native app'
description: 'Github Action to Dockerize a Quarkus native app'
branding:
  icon: 'anchor'
  color: 'yellow'
inputs:
    executablePath:
      description: 'path to the Quarkus executable you want to put in the docker image'
      required: true
    tag:
      description: 'docker tag to set once the image is built'
      required: true
    dockerfilePath:
      description: 'path to the Dockerfile you want to use - leave blank for default'
      required: false
outputs:
  image:
    description: 'Tagged docker image'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.executablePath }}
    - ${{ inputs.tag }}
    - ${{ inputs.dockerfilePath }}